function constant = constantFetcherFn(item,varargin)
% constantFetcherFn() - 
% fetches for a string or cell array of constants requested in item.
%
% Syntax - 
% constantFetcherFn(item,varargin).
%
% Parameters - 
% - item: item requested for fetching.
%
% Copyright -
% John S. H. Danial (2018). 
% danial@is.mpg.de

switch item
    
    %% retreiving shape descriptors
    case 'shapeDescriptor'
        analysisMethod = varargin{1};
        axis = varargin{2};
        switch axis
            case 'x'
                switch analysisMethod
                    case 'Pixel counting'
                        constant = {'Area',...
                            'Filled Area',...
                            'Convex Area',...
                            'Perimeter',...
                            'Euler Number',...
                            'Eccentricity',...
                            'Solidity',...
                            'Orientation',...
                            'Extent',...
                            'Major Axis Length',...
                            'Minor Axis Length',...
                            'Form Factor',...
                            'Roundness',...
                            'Elongation',...
                            'Fill Ratio',...
                            'Mean Intensity',...
                            'Minima Number',...
                            'Minima Intensity',...
                            'Minima Eccentricity',...
                            'Minima Area',...
                            'Minima Convex Area',...
                            'Maxima Number',...
                            'Maxima Intensity',...
                            'Maxima Eccentricity',...
                            'Maxima Area',...
                            'Maxima Convex Area',...
                            'Segment Total Length',...
                            'Segment Number Intersections',...
                            'Objects'};
                    case 'Ellipse fitting'
                        constant = {'Major Axis Length Fit',...
                            'Minor Axis Length Fit',...
                            'Elongation Fit',...
                            'Relative Centroid',...
                            'Orientation Fit'};
                    case 'Radial profiling'
                        constant = {'Distance'};
                    case 'Reserved'
                        constant = {'Label'};
                end
            case 'y'
                switch analysisMethod
                    case 'Pixel counting'
                        constant = {
                            'Area',...
                            'Filled Area',...
                            'Convex Area',...
                            'Perimeter',...
                            'Euler Number',...
                            'Eccentricity',...
                            'Solidity',...
                            'Orientation',...
                            'Extent',...
                            'Major Axis Length',...
                            'Minor Axis Length',...
                            'Form Factor',...
                            'Roundness',...
                            'Elongation',...
                            'Fill Ratio',...
                            'Mean Intensity',...
                            'Minima Number',...
                            'Minima Intensity',...
                            'Minima Eccentricity',...
                            'Minima Area',...
                            'Minima Convex Area',...
                            'Maxima Number',...
                            'Maxima Intensity',...
                            'Maxima Eccentricity',...
                            'Maxima Area',...
                            'Maxima Convex Area',...
                            'Segment Total Length',...
                            'Segment Number Intersections',...
                            'Objects'};
                    case 'Ellipse fitting'
                        constant = {
                            'Major Axis Length Fit',...
                            'Minor Axis Length Fit',...
                            'Elongation Fit',...
                            'Relative Centroid',...
                            'Orientation Fit'};
                        
                    case 'Radial profiling'
                        constant = {'Raw Radial Profile',...
                            'Intensity Normalized Radial Profile',...
                            'Area Normalized Radial Profile',...
                            'Raw Radial Density Profile',...
                            'Intensity Normalized Radial Density Profile',...
                            'Area Normalized Radial Density Profile'};
                    
                    case 'Reserved'
                        constant = {'Events',...
                            'Count'};
                end
        end
        
        %% retreiving analysis method provided a shape descriptor
    case 'analysisMethod'
        shapeDescriptor = varargin{1};
        axis = varargin{2};
        switch shapeDescriptor
            case constantFetcherFn('shapeDescriptor','Pixel counting',axis)
                constant = 'Pixel counting';
            case constantFetcherFn('shapeDescriptor','Ellipse fitting',axis)
                constant = 'Ellipse fitting';
            case constantFetcherFn('shapeDescriptor','Radial profiling',axis)
                constant = 'Radial profiling';
            case constantFetcherFn('shapeDescriptor','Reserved',axis)
                switch axis
                    case 'y'
                        constant = shapeDescriptor;
                end
        end
        %% retreiving type provided descriptors
    case 'type'
        xDescriptor = varargin{1};
        yDescriptor = varargin{2};
        if strcmp(yDescriptor,'Events')
            constant = 'Hist';
        elseif strcmp(yDescriptor,'Count')
            constant = 'Bar';
        elseif ~strcmp(yDescriptor,'Counts') && strcmp(xDescriptor,'Label')
            constant = 'Box';
        elseif strcmp(xDescriptor,'Distance')
            constant = 'Dot';
        else
            constant = 'Dot';
        end
        
        %% retreiving sub type provided type
    case 'subType'
        type = varargin{1};
        switch type
            case 'Bar'
                constant = {'Aligned bars',...
                    'Stacked bars'};
            case 'Dot'
                constant = {'Scatter',...
                    'Line',...
                    'Smooth',...
                    'Summary'};
            case 'Hist'
                constant = {'Bar',...
                    'Stacked bar',...
                    'Point',...
                    'Line',...
                    'Stairs'};
            case 'Box'
                constant = {'Box plot',...
                    'Violin',...
                    'Jittered'};
        end
        
        %% retrieving fit provided type
    case 'fit'
        type = varargin{1};
        switch type
            case 'Dot'
                constant = {'None',...
                    'Linear',...
                    'Quadratic',...
                    'Exponential',...
                    'Polynomial',...
                    'Custom'};
            case 'Hist'
                constant = {'None',...
                    'Density',...
                    'Normal'};
            otherwise
                constant = {'None'};
        end
        
        %% retrieving map
    case 'map'
        constant = {'lch',...
            'matlab',...
            'brewer1',...
            'brewer2',...
            'brewer3',...
            'brewer_pastel',...
            'brewer_dark',...
            'brewer_paired',...
            'd3_10',...
            'd3_20',...
            'd3_20b',...
            'd3_20c'};

        %% retrieving fill
    case 'fill'
        constant = {'All',...
            'Transparent',...
            'Edge',...
            'Face'};
        
        %% retrieving units
    case 'units'
        descriptor = varargin{1};
        switch descriptor
            case {'Area',...
                    'Filled Area',...
                    'Convex Area',...
                    'Minima Area',...
                    'Minima Convex Area',...
                    'Maxima Area',...
                    'Maxima Convex Area'}
                constant = '(nm^{2})';
            case {'Perimeter',...
                    'Major Axis Length',...
                    'Minor Axis Length',...
                    'Segment Total Length',...
                    'Segment Length',...
                    'SegmentRadius',...
                    'Distance'}
                constant = '(nm)';
            case {'Mean Intensity',...
                    'Minima Intensity',...
                    'Maxima Intensity'}
                constant = '(A.U)';
            case {'Orientation',...
                    'Segment Orientation'}
                constant = '(deg)';
            case {'Raw Radial Profile'}
                constant = 'Intensity (A.U.)';
            case {'Intensity Normalized Radial Profile',...
                    'Area Normalized Radial Profile'}
                constant = 'Normalized intensity (A.U.)';
            otherwise
                constant = '';
        end
end
end
